---
title: "FEC"
author: "David Kane"
date: "10/22/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(stringr)
library(fs)
```


```{r download_indiv, echo=FALSE, message=FALSE, cache=TRUE}
download.file(url = "https://www.fec.gov/files/bulk-downloads/1990/indiv90.zip",
              destfile = "indiv90.zip")

unzip("indiv90.zip")


indiv <- read_delim("itcont.txt", delim = "|", col_names = FALSE, escape_double = FALSE)

file_delete(c("indiv90.zip", "itcont.txt"))  
  
indiv %>% 
  transmute(name = X8, employer = X12, state = X10, amount = X15) %>% 
  filter(str_detect(employer, "HARVARD")) %>% 
  count(employer)
```


```{r download_com, echo=FALSE, message=FALSE, cache=TRUE}
download.file(url = "https://www.fec.gov/files/bulk-downloads/1990/cm90.zip",
              destfile = "cm90.zip")

unzip("cm90.zip")

cm <- read_delim("cm.txt", delim = "|", col_names = FALSE, escape_double = FALSE)

file_delete(c("cm90.zip", "cm.txt"))
```

